# Form implementation generated from reading ui file 'About_1.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(480, 220)
        About.setMinimumSize(QtCore.QSize(480, 220))
        About.setMaximumSize(QtCore.QSize(480, 220))
        self.results = QtWidgets.QLabel(About)
        self.results.setGeometry(QtCore.QRect(10, 10, 460, 201))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.results.setFont(font)
        self.results.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid #7b8691;")
        self.results.setWordWrap(False)
        self.results.setOpenExternalLinks(False)
        self.results.setObjectName("results")

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "О программе"))
        self.results.setText(_translate("About", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Клавиатурный тренажёр для студентов СПГУ &quot;Горняк&quot;</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">---------------------------------------</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Artem Akopyan</p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Copyright <span style=\" color:#333333; background-color:#ffffff;\">© </span>2022</p></body></html>"))
