# Form implementation generated from reading ui file 'Statistics_1.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Statistics(object):
    def setupUi(self, Statistics):
        Statistics.setObjectName("Statistics")
        Statistics.resize(460, 460)
        Statistics.setMinimumSize(QtCore.QSize(460, 460))
        Statistics.setMaximumSize(QtCore.QSize(460, 460))
        self.results = QtWidgets.QLabel(Statistics)
        self.results.setGeometry(QtCore.QRect(10, 10, 440, 150))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(12)
        self.results.setFont(font)
        self.results.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid #7b8691;")
        self.results.setWordWrap(False)
        self.results.setOpenExternalLinks(False)
        self.results.setObjectName("results")
        self.graphWidget = PlotWidget(Statistics)
        self.graphWidget.setEnabled(True)
        self.graphWidget.setGeometry(QtCore.QRect(10, 170, 440, 280))
        self.graphWidget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 4px solid #7b8691;")
        self.graphWidget.setObjectName("graphWidget")

        self.retranslateUi(Statistics)
        QtCore.QMetaObject.connectSlotsByName(Statistics)

    def retranslateUi(self, Statistics):
        _translate = QtCore.QCoreApplication.translate
        Statistics.setWindowTitle(_translate("Statistics", "РЕЗУЛЬТАТ"))
        self.results.setText(_translate("Statistics", "<html><head/><body><p>Время: 00:00</p><p>Количество символов: 0 из 0, ?%</p><p>Количество ошибок: 0, ?%</p><p>Скорость: 0 симв/мин</p></body></html>"))
from pyqtgraph import PlotWidget
